version: '3.4'
services:
  nginx:
    image: nginxproxy/nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: 'containous/whoami:latest'
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PATH: /whoami
      VIRTUAL_PORT: 80

  ghost:
    image: 'ghost:latest'
    environment:
      url: http://localhost/ghost
      VIRTUAL_HOST: localhost
      VIRTUAL_PATH: /ghost
      VIRTUAL_PORT: 2368

  ghost2:
    image: 'ghost:latest'
    environment:
     url: http://localhost/ghost2
     VIRTUAL_HOST: localhost
     VIRTUAL_PATH: /ghost2
     VIRTUAL_PORT: 2368

